language: python
python:
  - "3.7"
install:
  - "pip install -e .[dev]"
before_script:
  - "flake8 ."
  - "doc8 docs/"
script:
  - "sphinx-build -W -b html -d build/doctrees docs/source build/html"
  - "pytest -vvv --exitfirst --cov-fail-under 100 --cov todoer --cov storage"
cache:
  - pip
