authenticate:
  build: .
  ports:
   # HOST:CONTAINER

   # Flask defaults to listening on port 5000 but this is configurable.
   # See http://flask.pocoo.org/docs/0.10/api/#flask.Flask.run
   - "5000:5000"
  environment:
   # Set the environment variable SECRET_KEY else the secret will be insecure.
   - SECRET_KEY
  command: python authentication/authentication.py
  links:
    - storage
storage:
  build: .
  ports:
   # HOST:CONTAINER

   # Flask defaults to listening on port 5000 but this is configurable.
   # The storage service is configured to serve on 5001.
   # See http://flask.pocoo.org/docs/0.10/api/#flask.Flask.run
   - "5001:5001"
  volumes:
   - /tmp/authentication:/data
  environment:
   - SQLALCHEMY_DATABASE_URI=sqlite:////data/authentication.db
  command: python storage/storage.py
